[package]
name = "eonix"
version = "0.1.0"
edition = "2024"

[dependencies]
crossbeam-channel = "0.5.14"
rustc-hash = "2.1.1"



[features]
default = ["runtime-checks"]
large_tuples = []
runtime-checks = []